name = "VlasiatorMakie"
uuid = "af7e05b2-8ba0-474e-bf83-503ba399852e"
authors = ["Hongyang Zhou <hyzhou@umich.edu> and contributors"]
version = "0.1.3"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Vlasiator = "7d2ba682-ad6e-4e20-80d9-3f2d4a610bb4"

[compat]
Makie = "0.15"
StatsBase = "0.33"
Vlasiator = "0.8, 0.9"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
